name: release-on-push

on: [push]

permissions:
      contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cryptography
       # pip install pylint
   # - name: Analysing the code with pylint
     # run: |
       # pylint $(git ls-files '*.py')
    - name: Create Tarball
      run: |
        tar cfv cryptr_linux_en.tar source/en/launcher.py source/en/encrypter.py source/en/decrypter.py LICENSE
   # - name: Create Release
    #  id: create_release
     # uses: actions/create-release@v1
     # env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
     # with:
       # tag_name: ${{ github.ref }}
       # release_name: Release ${{ github.ref }}
       # draft: false
       # prerelease: true
    - name: Get short commit SHA
      id: get_sha
      run: echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
    - name: Create prerelease
      run: |
        gh release create "${{ steps.get_sha.outputs.short_sha }}" cryptr_linux_en.tar --title "Prerelease ${{ steps.get_sha.outputs.short_sha }}" --prerelease
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}