name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Create Tarball
      run: |
        tar cfv cryptr_linux.tar source/en/launcher.py source/en/encrypter.py source/en/decrypter.py LICENSE
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: linux-tarball
        path: cryptr_linux.tar