name: prerelease-on-push

on:
  push:
    tags:
      - pre*-v*

permissions:
      contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cryptography
       # pip install pylint
   # - name: Analysing the code with pylint
     # run: |
       # pylint $(git ls-files '*.py')
    - name: Create ZIP
      run: |
        zip cryptr_win_pre.zip source/launcher.py source/encrypter.py source/decrypter.py LICENSE
    - name: Create Tarball
      run: |
        tar cfv cryptr_linux_pre.tar source/launcher.py source/encrypter.py source/decrypter.py LICENSE
    #- name: Create Release
    #  id: create_release
     # uses: actions/create-release@v1
     # env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
     # with:
       # tag_name: ${{ github.ref }}
       # release_name: Release ${{ github.ref }}
       # draft: false
       # prerelease: true
    - name: Create prerelease
      run: |
        gh release create "$TAG" cryptr_linux_pre.tar cryptr_win_pre.zip --title "Prerelease $TAG" --prerelease
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}