on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

permissions:
        contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     # - name: Create Release
       # id: create_release
       # uses: actions/create-release@v1
       # env:
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
       # with:
          # tag_name: ${{ github.ref }}
         # release_name: Release ${{ github.ref }}
         # draft: false
         # prerelease: false
      - name: Create ZIP
        run: |
          zip cryptr_win.zip source/launcher.py source/encrypter.py source/decrypter.py LICENSE
      - name: Create Tarball
        run: |
          tar cfv cryptr_linux.tar source/launcher.py source/encrypter.py source/decrypter.py LICENSE
      - name: Create release
        run: |
          gh release create "$TAG" cryptr_linux.tar cryptr_win.zip --title "Release $TAG"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}